sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 12315
  redis:
    host: localhost
    port: 6379
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id:
    access-key-secret:
    bucket-name: sky-take-out-xuan
  wechat:
    appid: wx2fe0085856c9a163
    secret: 17d1ed9d0a903fb4639db52f0ba69a76
    mchid : 1561414331
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    privateKeyFilePath: D:\apiclient_key.pem
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    weChatPayCertFilePath: D:\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl:  https://17b2f0d7.r16.vip.cpolar.cn/notify/paySuccess
    refundNotifyUrl: https://17b2f0d7.r16.vip.cpolar.cn/notify/refundSuccess